language: python
python:
  - "3.6"

before_install:
- sed '/django-heroku==/d' requirements.txt > requirements-build.txt
install:
- pip install -r requirements-build.txt
before_script:
- python manage.py migrate --settings=rsoi_project.settings
script:
- python manage.py test